version: '3'

services:
  user_sshd_00:
    image: baseimage:adduser
    ports:
      - "20022:22"
      - "20080:80"
      - "20011:4011"
    environment:
      - NEWUSERNAME=ksuser00
      - NEWPASSWORD='`^}Qhnk8?
    volumes:
      - /home/prj/00:/home

  user_sshd_01:
    image: baseimage:adduser
    ports:
      - "20122:22"
      - "20180:80"
      - "20111:4011"
    environment:
      - NEWUSERNAME=ksuser01
      - NEWPASSWORD=(,Sz3ppf>P
    volumes:
      - /home/prj/01:/home

  user_sshd_02:
    image: baseimage:adduser
    ports:
      - "20222:22"
      - "20280:80"
      - "20211:4011"
    environment:
      - NEWUSERNAME=ksuser02
      - NEWPASSWORD=NKOPVug&*#
    volumes:
      - /home/prj/02:/home

  user_sshd_03:
    image: baseimage:adduser
    ports:
      - "20322:22"
      - "20380:80"
      - "20311:4011"
    environment:
      - NEWUSERNAME=ksuser03
      - NEWPASSWORD=rnzn;n7n\H
    volumes:
      - /home/prj/03:/home

  user_sshd_04:
    image: baseimage:adduser
    ports:
      - "20422:22"
      - "20480:80"
      - "20411:4011"
    environment:
      - NEWUSERNAME=ksuser04
      - NEWPASSWORD=z6,DyM[b_b
    volumes:
      - /home/prj/04:/home

  user_sshd_05:
    image: baseimage:adduser
    ports:
      - "20522:22"
      - "20580:80"
      - "20511:4011"
    environment:
      - NEWUSERNAME=ksuser05
      - NEWPASSWORD=6A%S*S!3O(
    volumes:
      - /home/prj/05:/home

  user_sshd_06:
    image: baseimage:adduser
    ports:
      - "20622:22"
      - "20680:80"
      - "20611:4011"
    environment:
      - NEWUSERNAME=ksuser06
      - NEWPASSWORD=#M>XpAe;PO
    volumes:
      - /home/prj/06:/home

  user_sshd_07:
    image: baseimage:adduser
    ports:
      - "20722:22"
      - "20780:80"
      - "20711:4011"
    environment:
      - NEWUSERNAME=ksuser07
      - NEWPASSWORD=G?`T*#Qy*x
    volumes:
      - /home/prj/07:/home

  user_sshd_08:
    image: baseimage:adduser
    ports:
      - "20822:22"
      - "20880:80"
      - "20811:4011"
    environment:
      - NEWUSERNAME=ksuser08
      - NEWPASSWORD=5tkiyLuT2!
    volumes:
      - /home/prj/08:/home

  user_sshd_09:
    image: baseimage:adduser
    ports:
      - "20922:22"
      - "20980:80"
      - "20911:4011"
    environment:
      - NEWUSERNAME=ksuser09
      - NEWPASSWORD=DfSMPLoj]p
    volumes:
      - /home/prj/09:/home

  user_sshd_10:
    image: baseimage:adduser
    ports:
      - "21022:22"
      - "21080:80"
      - "21011:4011"
    environment:
      - NEWUSERNAME=ksuser10
      - NEWPASSWORD=Az~JmFrugK
    volumes:
      - /home/prj/10:/home

  user_sshd_11:
    image: baseimage:adduser
    ports:
      - "21122:22"
      - "21180:80"
      - "21111:4011"
    environment:
      - NEWUSERNAME=ksuser11
      - NEWPASSWORD=;XC<MsLKF6
    volumes:
      - /home/prj/11:/home

  user_sshd_12:
    image: baseimage:adduser
    ports:
      - "21222:22"
      - "21280:80"
      - "21211:4011"
    environment:
      - NEWUSERNAME=ksuser12
      - NEWPASSWORD=QJuiSLE,5r
    volumes:
      - /home/prj/12:/home

  user_sshd_13:
    image: baseimage:adduser
    ports:
      - "21322:22"
      - "21380:80"
      - "21311:4011"
    environment:
      - NEWUSERNAME=ksuser13
      - NEWPASSWORD=VgRr@qP(qb
    volumes:
      - /home/prj/13:/home

  user_sshd_14:
    image: baseimage:adduser
    ports:
      - "21422:22"
      - "21480:80"
      - "21411:4011"
    environment:
      - NEWUSERNAME=ksuser14
      - NEWPASSWORD=pOiyD=>;ut
    volumes:
      - /home/prj/14:/home

  user_sshd_15:
    image: baseimage:adduser
    ports:
      - "21522:22"
      - "21580:80"
      - "21511:4011"
    environment:
      - NEWUSERNAME=ksuser15
      - NEWPASSWORD=KSoO)xTi;y
    volumes:
      - /home/prj/15:/home

  user_sshd_16:
    image: baseimage:adduser
    ports:
      - "21622:22"
      - "21680:80"
      - "21611:4011"
    environment:
      - NEWUSERNAME=ksuser16
      - NEWPASSWORD=fG]cJjZE#s
    volumes:
      - /home/prj/16:/home

  user_sshd_17:
    image: baseimage:adduser
    ports:
      - "21722:22"
      - "21780:80"
      - "21711:4011"
    environment:
      - NEWUSERNAME=ksuser17
      - NEWPASSWORD=jU&T!Zh%Tz
    volumes:
      - /home/prj/17:/home

  user_sshd_18:
    image: baseimage:adduser
    ports:
      - "21822:22"
      - "21880:80"
      - "21811:4011"
    environment:
      - NEWUSERNAME=ksuser18
      - NEWPASSWORD=9/xs0t4?pU
    volumes:
      - /home/prj/18:/home

  user_sshd_19:
    image: baseimage:adduser
    ports:
      - "21922:22"
      - "21980:80"
      - "21911:4011"
    environment:
      - NEWUSERNAME=ksuser19
      - NEWPASSWORD=JX>u-"o)y.
    volumes:
      - /home/prj/19:/home

  user_sshd_20:
    image: baseimage:adduser
    ports:
      - "22022:22"
      - "22080:80"
      - "22011:4011"
    environment:
      - NEWUSERNAME=ksuser20
      - NEWPASSWORD=g3NN7;GKqM
    volumes:
      - /home/prj/20:/home

  user_sshd_21:
    image: baseimage:adduser
    ports:
      - "22122:22"
      - "22180:80"
      - "22111:4011"
    environment:
      - NEWUSERNAME=ksuser21
      - NEWPASSWORD=#hPLsAKBz;
    volumes:
      - /home/prj/21:/home

  user_sshd_22:
    image: baseimage:adduser
    ports:
      - "22222:22"
      - "22280:80"
      - "22211:4011"
    environment:
      - NEWUSERNAME=ksuser22
      - NEWPASSWORD=\pzFEGBmT|
    volumes:
      - /home/prj/22:/home

  user_sshd_23:
    image: baseimage:adduser
    ports:
      - "22322:22"
      - "22380:80"
      - "22311:4011"
    environment:
      - NEWUSERNAME=ksuser23
      - NEWPASSWORD=o]M?nooH%t
    volumes:
      - /home/prj/23:/home

  user_sshd_24:
    image: baseimage:adduser
    ports:
      - "22422:22"
      - "22480:80"
      - "22411:4011"
    environment:
      - NEWUSERNAME=ksuser24
      - NEWPASSWORD=|x%mxW4H!(
    volumes:
      - /home/prj/24:/home

  user_sshd_25:
    image: baseimage:adduser
    ports:
      - "22522:22"
      - "22580:80"
      - "22511:4011"
    environment:
      - NEWUSERNAME=ksuser25
      - NEWPASSWORD=Nf8wy;C~<Y
    volumes:
      - /home/prj/25:/home

  user_sshd_26:
    image: baseimage:adduser
    ports:
      - "22622:22"
      - "22680:80"
      - "22611:4011"
    environment:
      - NEWUSERNAME=ksuser26
      - NEWPASSWORD=NwEL9'GLwB
    volumes:
      - /home/prj/26:/home

  user_sshd_27:
    image: baseimage:adduser
    ports:
      - "22722:22"
      - "22780:80"
      - "22711:4011"
    environment:
      - NEWUSERNAME=ksuser27
      - NEWPASSWORD=mEYSEtaE_Z
    volumes:
      - /home/prj/27:/home

  user_sshd_28:
    image: baseimage:adduser
    ports:
      - "22822:22"
      - "22880:80"
      - "22811:4011"
    environment:
      - NEWUSERNAME=ksuser28
      - NEWPASSWORD=fRaaKfrLZf
    volumes:
      - /home/prj/28:/home

  user_sshd_29:
    image: baseimage:adduser
    ports:
      - "22922:22"
      - "22980:80"
      - "22911:4011"
    environment:
      - NEWUSERNAME=ksuser29
      - NEWPASSWORD=SjV4P0GtMp
    volumes:
      - /home/prj/29:/home

  user_sshd_30:
    image: baseimage:adduser
    ports:
      - "23022:22"
      - "23080:80"
      - "23011:4011"
    environment:
      - NEWUSERNAME=ksuser30
      - NEWPASSWORD=GAxm~bZ,0C
    volumes:
      - /home/prj/30:/home

  user_sshd_31:
    image: baseimage:adduser
    ports:
      - "23122:22"
      - "23180:80"
      - "23111:4011"
    environment:
      - NEWUSERNAME=ksuser31
      - NEWPASSWORD=OG!;waDrj)
    volumes:
      - /home/prj/31:/home

  user_sshd_32:
    image: baseimage:adduser
    ports:
      - "23222:22"
      - "23280:80"
      - "23211:4011"
    environment:
      - NEWUSERNAME=ksuser32
      - NEWPASSWORD=%BX3m,v"Lk
    volumes:
      - /home/prj/32:/home

  user_sshd_33:
    image: baseimage:adduser
    ports:
      - "23322:22"
      - "23380:80"
      - "23311:4011"
    environment:
      - NEWUSERNAME=ksuser33
      - NEWPASSWORD=.f!AOjvOfY
    volumes:
      - /home/prj/33:/home

  user_sshd_34:
    image: baseimage:adduser
    ports:
      - "23422:22"
      - "23480:80"
      - "23411:4011"
    environment:
      - NEWUSERNAME=ksuser34
      - NEWPASSWORD=y(0P;>r^f8
    volumes:
      - /home/prj/34:/home

  user_sshd_35:
    image: baseimage:adduser
    ports:
      - "23522:22"
      - "23580:80"
      - "23511:4011"
    environment:
      - NEWUSERNAME=ksuser35
      - NEWPASSWORD=uWQrJuIOX0
    volumes:
      - /home/prj/35:/home

  user_sshd_36:
    image: baseimage:adduser
    ports:
      - "23622:22"
      - "23680:80"
      - "23611:4011"
    environment:
      - NEWUSERNAME=ksuser36
      - NEWPASSWORD=hrf;W&*idt
    volumes:
      - /home/prj/36:/home

  user_sshd_37:
    image: baseimage:adduser
    ports:
      - "23722:22"
      - "23780:80"
      - "23711:4011"
    environment:
      - NEWUSERNAME=ksuser37
      - NEWPASSWORD=iaYJhPF|vw
    volumes:
      - /home/prj/37:/home

  user_sshd_38:
    image: baseimage:adduser
    ports:
      - "23822:22"
      - "23880:80"
      - "23811:4011"
    environment:
      - NEWUSERNAME=ksuser38
      - NEWPASSWORD=KA(DvqhwLf
    volumes:
      - /home/prj/38:/home

  user_sshd_39:
    image: baseimage:adduser
    ports:
      - "23922:22"
      - "23980:80"
      - "23911:4011"
    environment:
      - NEWUSERNAME=ksuser39
      - NEWPASSWORD=sRe\MFohe|
    volumes:
      - /home/prj/39:/home
